In [1]:
import pandas as pd

In [2]:
import nltk

# Download the missing WordNet resource
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/josecerqueira/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [3]:
web_scrape_comments = pd.read_csv("web_scrape_comments.csv")

In [4]:
web_scrape_comments

,id,name,anonymous,hostProgramName,graduatingYear,isAlumni,jobTitle,tagline,body,rawBody,...,queryDate,program,user,overallScore,comments,overall,curriculum,jobSupport,review_body,school
0,306372,Sergio Burgos,False,NaN,2023.0,False,International Negotiator,The Most Intense Academic Challenge,"<span class=""truncatable""><p></p><p>After comp...",<p>After completing my Data Analytics Bootcamp...,...,2023-11-10,Data Analytics Bootcamp,{'image': None},3.3,[],3.0,3.0,4.0,After completing my Data Analytics Bootcamp wi...,ironhack
1,306215,Anonymous,True,NaN,2023.0,True,NaN,Transformative Experience: My Time at Ironhack,"<span class=""truncatable""><p></p><p>Pros: 1)In...",<p>Pros: 1)Intensive Learning 2)Real-World Pro...,...,2023-11-06,Web Development Bootcamp,{'image': None},4.0,[],4.0,4.0,4.0,Pros: 1)Intensive Learning 2)Real-World Projec...,ironhack
2,306068,Anonymous,True,NaN,2023.0,False,Full stack development,Now I can do it,"<span class=""truncatable""><p></p><p>7 months a...","<p>7 months ago, I only had an idea about html...",...,2023-10-31,NaN,{'image': None},5.0,[],5.0,5.0,5.0,"7 months ago, I only had an idea about html an...",ironhack
3,305297,Utku Cikmaz,False,NaN,2023.0,False,Full Stack Web Developer,It was good,"<span class=""truncatable""><p></p><p>The course...","<p>The course was great. Especially, Luis is a...",...,2023-10-02,Web Development Bootcamp,{'image': None},4.0,[],5.0,3.0,4.0,"The course was great. Especially, Luis is a gr...",ironhack
4,305278,Nirmal Hodge,False,NaN,2023.0,False,Product Designer,Ironhack 100% Worth It!,"<span class=""truncatable""><p></p><p>I joined t...",<p>I joined the UX/ UI Bootcamp and to be hone...,...,2023-09-30,UX/UI Design Bootcamp,{'image': None},5.0,[],5.0,5.0,5.0,I joined the UX/ UI Bootcamp and to be honest ...,ironhack
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4037,234894,Stephanie S.,False,NaN,2015.0,True,Website Manager-UX Lead,Excellent and comprehensive UX course,"<span class=""truncatable""><p>The UX Design Wor...",The UX Design Workshop gave me a great underst...,...,2016-12-15,UX Design,{'image': None},5.0,[],5.0,5.0,5.0,The UX Design Workshop gave me a great underst...,springboard
4038,234877,Joe Fang,False,NaN,2015.0,True,UX Designer,Springboard helped me start my career in UX,"<span class=""truncatable""><p>Just some backgro...","Just some background information on myself, I ...",...,2016-12-15,UX Design,{'image': None},5.0,[],5.0,5.0,5.0,"Just some background information on myself, I ...",springboard
4039,234838,Zeina,False,NaN,2016.0,True,Senior Graphic Designer,Highly recommended,"<span class=""truncatable""><p>I enjoyed the pro...","I enjoyed the program very much, gained a lot ...",...,2016-12-15,UX Design,{'image': None},3.7,[],4.0,4.0,3.0,"I enjoyed the program very much, gained a lot ...",springboard
4040,242681,Jean,False,NaN,2016.0,True,Lead Designer/Creative Director,A way to stay current for the highly motivated!,"<span class=""truncatable""><p>This was my first...",This was my first online experience and it did...,...,2016-12-12,UX Design,{'image': None},5.0,[],5.0,5.0,5.0,This was my first online experience and it did...,springboard
4041,234178,Ben,False,NaN,2016.0,True,NaN,Springboard is an excellent course for self dr...,"<span class=""truncatable""><p>I really enjoyed ...",I really enjoyed my time with the Springboard ...,...,2016-12-10,UX Design,{'image': None},4.7,[],5.0,5.0,4.0,I really enjoyed my time with the Springboard ...,springboard

In [5]:
import nltk
import pandas as pd
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.corpus import wordnet

# Download NLTK resources
nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/josecerqueira/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/josecerqueira/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/josecerqueira/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

## Function to get synonyms:

In [6]:
def get_synonyms(word):
    synonyms = []
    for syn in wordnet.synsets(word):
        for lemma in syn.lemmas():
            synonyms.append(lemma.name())
    return synonyms

In [7]:
def filter_improvement_comments(comment):
    words = word_tokenize(comment.lower())
    
    words = [word for word in words if word.isalnum() and word not in stopwords.words("english")]

    target_word = "improvement"
    synonyms = get_synonyms(target_word)
    
    return any(word in words for word in [target_word] + synonyms)

In [8]:
filtered_web_scrape_comments = web_scrape_comments[web_scrape_comments["review_body"].apply(filter_improvement_comments)]

# Display the filtered DataFrame
filtered_web_scrape_comments

,id,name,anonymous,hostProgramName,graduatingYear,isAlumni,jobTitle,tagline,body,rawBody,...,queryDate,program,user,overallScore,comments,overall,curriculum,jobSupport,review_body,school
76,295724,Paola,False,NaN,2020.0,False,PM Fintech,One of the best decisions I've ever made,"<span class=""truncatable""><p></p><p>I was in t...",<p>I was in the data analytics part time bootc...,...,2022-12-12,Data Analytics Part-Time,{'image': None},3.7,[],4.0,3.0,4.0,I was in the data analytics part time bootcamp...,ironhack
139,293171,João Cabral,False,NaN,2022.0,False,Data Analyst student,It was one of the most empowering experiences ...,"<span class=""truncatable""><p></p><p>I really h...",<p>I really have to take some time to speak ab...,...,2022-09-21,Data Analytics Bootcamp,{'image': None},5.0,[],5.0,5.0,5.0,I really have to take some time to speak about...,ironhack
166,289606,Anonymous,True,NaN,2022.0,False,Junior Data Analyst,An amazing and intense learning experience!,"<span class=""truncatable""><p></p><p>It was an ...",<p>It was an amazing experience to learn from ...,...,2022-06-09,Data Analytics Bootcamp,{'image': None},4.7,[],4.0,5.0,5.0,It was an amazing experience to learn from gre...,ironhack
183,286102,Dafne Lopez,False,NaN,2022.0,False,UX/UI Designer,It was fast and furious! And very insightful,"<span class=""truncatable""><p></p><p>Recently I...",<p>Recently I became a proud Ironhack Alumni! ...,...,2022-02-22,UX/UI Design Bootcamp,{'image': None},4.7,[],5.0,4.0,5.0,Recently I became a proud Ironhack Alumni! I d...,ironhack
243,275872,Ahmad Khalaf,False,NaN,2021.0,False,Product Designer,Intense but good experience,"<span class=""truncatable""><p></p><p>When I sta...",<p>When I started I was a little disappointed ...,...,2021-04-15,UX/UI Design Bootcamp,{'image': None},4.0,[],4.0,4.0,4.0,When I started I was a little disappointed but...,ironhack
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3864,245878,Jonas Cuadrado,False,Data Science,2018.0,True,NaN,"Deep, well structured course","<span class=""truncatable""><p>I recently comple...",I recently completed the Data Science career t...,...,2018-12-09,Data Science Career Track,{'image': None},5.0,[],5.0,5.0,5.0,I recently completed the Data Science career t...,springboard
3976,243423,Katie Fitton,False,UX/UI Design,2018.0,True,NaN,Practical experience with project-focused appr...,"<span class=""truncatable""><p>Springboard has a...","Springboard has a practical, relevant, and pro...",...,2018-03-29,UX Design,{'image': None},4.0,[],4.0,5.0,3.0,"Springboard has a practical, relevant, and pro...",springboard
4020,235481,Landon Barnickle,False,NaN,2017.0,True,Consulting Software Engineer,Mentor Led Deep Dive into Data Science,"<span class=""truncatable""><p>Springboard's Dat...",Springboard's Data Science Intensive is a grea...,...,2017-03-24,Intermediate Data Science,{'image': None},5.0,[],5.0,5.0,5.0,Springboard's Data Science Intensive is a grea...,springboard
4021,235228,Anonymous,False,NaN,2016.0,True,Business Analyst,Do you got what it takes?,"<span class=""truncatable""><p>This course was a...",This course was a great and fair step in helpi...,...,2017-03-24,Introduction to Data Science,{'image': None},4.0,[],4.0,4.0,4.0,This course was a great and fair step in helpi...,springboard
4030,232997,Shivani S.,False,NaN,2016.0,True,Data Analyst,If you want to start excelling at Data Science...,"<span class=""truncatable""><p>My prime goal wit...",My prime goal with this course was to advance ...,...,2016-12-21,Introduction to Data Science,{'image': None},5.0,[],5.0,5.0,NaN,My prime goal with this course was to advance ...,springboard

In [9]:
filtered_web_scrape_comments_2 = filtered_web_scrape_comments["review_body"]

In [10]:
file_path = 'web_scrape_comments_improved.csv'

# Save the DataFrame to a CSV file
filtered_web_scrape_comments_2.to_csv(file_path, index=False)

In [12]:
pd.DataFrame(filtered_web_scrape_comments_2)

                                            review_body
76    I was in the data analytics part time bootcamp...
139   I really have to take some time to speak about...
166   It was an amazing experience to learn from gre...
183   Recently I became a proud Ironhack Alumni! I d...
243   When I started I was a little disappointed but...
...                                                 ...
3864  I recently completed the Data Science career t...
3976  Springboard has a practical, relevant, and pro...
4020  Springboard's Data Science Intensive is a grea...
4021  This course was a great and fair step in helpi...
4030  My prime goal with this course was to advance ...

[82 rows x 1 columns]

In [13]:
filtered_web_scrape_comments_2

76      I was in the data analytics part time bootcamp...
139     I really have to take some time to speak about...
166     It was an amazing experience to learn from gre...
183     Recently I became a proud Ironhack Alumni! I d...
243     When I started I was a little disappointed but...
                              ...
3864    I recently completed the Data Science career t...
3976    Springboard has a practical, relevant, and pro...
4020    Springboard's Data Science Intensive is a grea...
4021    This course was a great and fair step in helpi...
4030    My prime goal with this course was to advance ...
Name: review_body, Length: 82, dtype: object